### ISSUE TITLE
NFS service fails to start

### ISSUE THREAD

**Issue by realflash** [eduardocardoso/s3fs-container#7]
On a stock current Mint installation, nfs fails to start with:

```
Not starting NFS kernel daemon: no support in current kernel. ... (warning).
```

This is because the required kernel modules are not loaded in the host's kernel by defaullt. To fix this, add the following two lines to the bottom of _/etc/modules_:

```
nfs
nfsd
```

Then reboot. This ensures the required kernel modules are loaded into the running kernel before the docker container starts.

**Comment by eduardocardoso** [comment]
Fixed by #8
